service: ransomwhere
useDotenv: true

custom:
  bucket: ransomwhere

provider:
  name: aws

  runtime: nodejs14.x
  iam.role.statements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::ransomwhere"

plugins:
  - serverless-offline

functions:
  list:
    handler: api.list
    events:
      - http:
          path: list
          method: get
          cors: true

  submit:
    handler: api.submit
    events:
      - http:
          path: submit
          method: post
          cors: true

  reports:
    handler: api.reports
    events:
      - http:
          path: reports
          method: post
          cors: true

  # getS3URL:
  #   handler: api.getS3
  #   events:
  #     - http:
  #         path: s3
  #         method: post
  #         cors: true

  updateReport:
    handler: api.updateReport
    events:
      - http:
          path: reports/{id}
          method: post
          cors: true

  update:
    handler: cron.update
    timeout: 900
    events:
      - schedule: rate(1 hour)

  import:
    handler: cron.import